export const EXPERIENCES = [
  {
    duration: "December 2023 - January 2024",
    iconClassName: "bg-primary p-[2px]",
    icon: "/experience/zentech.png",
    organization: "ZenTech Systems",
    role: "Full Stack Web Developer",
    type: "Freelancing",
    skills: ["react", "nextjs", "nodejs", "mongodb", "git", "github"],
    descriptions: [
      "Collaborated in a 4-member team at ZenTech Systems, leading backend API development.",
      "Contributed to frontend UI enhancements and seamless API integrations.",
      "Key role in designing and planning the initial system.",
    ],
  },
  {
    duration: "August 2023 - Present",
    iconClassName: "bg-white",
    icon: "/experience/acm.png",
    organization: "MHSSCOE ACM",
    role: "Webmaster (Web Team Lead)",
    type: "Leadership",
    skills: ["react", "nextjs", "nodejs", "mongodb", "git", "github"],
    descriptions: [
      "Led a 4-member team in developing a responsive web app for ACM.",
      "Handled full-stack development, designing the entire system.",
      "Managed execution planning, collaborating closely with the team for project success.",
    ],
  },
  {
    duration: "January - June 2023",
    iconClassName: "bg-white",
    icon: "/experience/cognitio.png",
    organization: "Cognitio Knowledge Tech Private Limited",
    role: "Frontend Web Developer",
    type: "Internship",
    skills: ["react", "redux", "git", "github"],
    descriptions: [
      "Collaborated with a team of 5 in developing responsive UIs from provided Figma designs.",
      "Contributed significantly to the creation of the entire frontend.",
      "Played a key role in integrating provided APIs, enhancing the functionality of the system.",
    ],
  },
  {
    duration: "January 2021 - June 2024",
    iconClassName: "bg-primary",
    icon: "/experience/mhssce.png",
    organization: "M. H. Saboo Siddik College of Engineering",
    role: "B. E. - Information Technology",
    type: "Education",
    // skills: ["react", "redux", "git", "github"],
    descriptions: [
      "Earned a comprehensive B.E. degree in Information Technology.",
      "Led and participated in diverse hands-on projects, refining practical skills.",
      "Thrived in collaborative teamwork, contributing effectively to group success.",
    ],
  },
];
